### ISSUE TITLE
Syntas error

### ISSUE THREAD

**Issue by xXxLASTANDxXx** [gilbertohasnofb/cyberpunk-syntax#1]
I have downloaded the mod and set my key. Went into the game and have tried ever money cheat command I have found and I keep getting errors. I have triple checked my work and cannot figure out what the hell I'm doing wrong.

Please help. Thank you.

**Comment by gilbertohasnofb** [comment]
Hi, I'm not sure what do you mean by game. This is a package for Atom, a text editor. All it does is change the theme of this text editor (i.e. change the text colouring). Could you clarify what's exactly the issue you are facing?

**Comment by xXxLASTANDxXx** [comment]
Thank you for your reply. Yes, I am not tech savvy so I know it's me lol. I
thought you had to have a mod to enter game commands on cyberpunk 2077.
When I enter codes it gives me a Syntex error message.

Can you guide me to what I need to do game commands? I would much
appreciate it.

Sorry for the confusion.

Justin

**Comment by gilbertohasnofb** [comment]
Hi Justin, no worries about it! But I think there is a misunderstanding here, this repository has nothing to do with the game Cyuberpunk 2077, this is just a little theme I wrote for a text editor named Atom and which is completely unrelated to the game. I see how you might have come across this repository given that the name is `cyberpunk-syntax`, but this name only relates to the [Cyberpunk genre of sci-fi](https://www.wikiwand.com/en/Cyberpunk), which often uses neon colours just like this theme. But that is just a name, in the end all this does is change the colours of the Atom text editor.

> Can you guide me to what I need to do game commands?

I'm really not sure about that one! Maybe you can try looking at the game forum if there is one (or Reddit!).

Cheers!

**Comment by xXxLASTANDxXx** [comment]
Well shoot. I told you I'm not tech savvy lol. I'm a console kind of guy
not a computer guy. Sorry for wasting your time. But thank you for clearing
my misunderstanding up.

Take care,

Justin

**Comment by xXxLASTANDxXx** [comment]
Oh yes! This is where I read from that gave me this idea.

https://www.digitaltrends.com/gaming/cyberpunk-2077-cheats-and-hacks/#:~:text=With%20the%20mod%20installed%2C%20open,to%20enter%20the%20right%20commands
.

**Comment by gilbertohasnofb** [comment]
No worries at all, Justin! I hope you'll find the answers for this elsewhere! Good luck :smiley:

**Comment by xXxLASTANDxXx** [comment]
Thank you!
